# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-29 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=63)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('hashtags', models.ManyToManyField(to='endpoint.Hashtag')),
            ],
        ),
        migrations.AddField(
            model_name='emotion',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoint.Recording'),
        ),
    ]
