# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-29 08:43
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='recording',
        ),
        migrations.AddField(
            model_name='recording',
            name='emotions',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
