# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-30 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0003_recording_clip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='date',
        ),
    ]
