# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-30 07:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0005_auto_20170730_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='filename',
        ),
        migrations.AlterField(
            model_name='recording',
            name='emotions',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
