# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-30 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0007_auto_20170730_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='angry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recording',
            name='fear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recording',
            name='happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recording',
            name='neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recording',
            name='sad',
            field=models.IntegerField(default=0),
        ),
    ]
