# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0009_auto_20170730_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='transcript',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
