# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0010_auto_20170730_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='recording',
            name='categories',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
